name = "MultiObjectiveAlgorithms"
uuid = "0327d340-17cd-11ea-3e99-2fd5d98cecda"
authors = ["Oscar Dowson <o.dowson@gmail.com>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[compat]
Combinatorics = "1"
HiGHS = "1"
MathOptInterface = "1.12"
julia = "1.6"

[extras]
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["HiGHS", "Test"]
